In [1]:
import pandas as pd

In [2]:
data =pd.DataFrame({"Name":["vinoth","kavin","arun","vishnu"],
       "Age":[20,30,25,19],})
data

     Name  Age
0  vinoth   20
1   kavin   30
2    arun   25
3  vishnu   19

In [3]:
print(pd.__version__)

2.3.1

In [4]:
a=pd.Series([88,45,56,56])
print(a)

0    88
1    45
2    56
3    56
dtype: int64

In [5]:
print(a[0])
print(a[2])
print(a[1])

88
56
45

In [6]:
b=[1,2,33,41]
my=pd.Series(b,index=["X","Y","Z","A"])
print(my)

X     1
Y     2
Z    33
A    41
dtype: int64

In [7]:
Data = {"vinoth":67,"kavin":65,"arun":34,"vishnu":2}
vin=pd.Series(Data["kavin"])
vin

0    65
dtype: int64

In [8]:
# loc location
df=pd.DataFrame([Data])
print(df.loc[[0]])

   vinoth  kavin  arun  vishnu
0      67     65    34       2

In [9]:
smartphones=pd.read_csv("cleaned_data.csv")
smartphones.head()

,model,price,rating,os,sim_type,network_type,VoLTE,NFC,ir_blaster,chipset,...,resolution,refresh_rate_hz,display_type,rear_camera_mp_list,rear_camera_count,rear_camera_max_mp,front_camera_mp,memory_card_supported,memory_card_type,memory_card_max_gb
0,oneplus 11 5g,54999,89.0,Android v13,Dual,5g,True,True,False,Snapdragon 8 Gen2,...,1440x3216,120.0,Punch Hole,"[50, 48, 32]",3,50.0,16.0,1,NaN,NaN
1,oneplus nord ce 2 lite 5g,19989,81.0,Android v12,Dual,5g,True,False,False,Snapdragon 695,...,1080x2412,120.0,Punch Hole,"[64, 2, 2]",3,64.0,16.0,1,Hybrid,1024.0
2,samsung galaxy a14 5g,16499,75.0,Android v13,Dual,5g,True,False,False,Exynos 1330,...,1080x2408,90.0,Water Drop Notch,"[50, 2, 2]",3,50.0,13.0,1,Dedicated,1024.0
3,motorola moto g62 5g,14999,81.0,Android v12,Dual,5g,True,False,False,Snapdragon 695,...,1080x2400,120.0,Punch Hole,"[50, 8, 2]",3,50.0,16.0,1,Hybrid,1024.0
4,realme 10 pro plus,24999,82.0,Android v13,Dual,5g,True,False,False,Dimensity 1080,...,1080x2412,120.0,Punch Hole,"[108, 8, 2]",3,108.0,16.0,1,NaN,NaN

In [10]:
smartphones.tail()

,model,price,rating,os,sim_type,network_type,VoLTE,NFC,ir_blaster,chipset,...,resolution,refresh_rate_hz,display_type,rear_camera_mp_list,rear_camera_count,rear_camera_max_mp,front_camera_mp,memory_card_supported,memory_card_type,memory_card_max_gb
963,motorola moto edge s30 pro,34990,83.0,Android v12,Dual,5g,True,False,False,Snapdragon 8 Gen1,...,1080x2460,120.0,Punch Hole,"[64, 8, 2]",3,64.0,16.0,1,Dedicated,NaN
964,honor x8 5g,14990,75.0,Android v11,Dual,5g,True,False,False,Snapdragon 480+,...,720x1600,NaN,Water Drop Notch,"[48, 2]",2,48.0,8.0,1,Dedicated,1024.0
965,poco x4 gt 5g,28990,85.0,Android v12,Dual,5g,True,True,True,Dimensity 8100,...,1080x2460,144.0,Punch Hole,"[64, 8, 2]",3,64.0,16.0,1,NaN,NaN
966,motorola moto g91 5g,19990,80.0,Android v12,Dual,5g,True,True,False,Snapdragon 695,...,1080x2400,NaN,Punch Hole,"[108, 8, 2]",3,108.0,32.0,1,Dedicated,1024.0
967,samsung galaxy m52s 5g,24990,74.0,Android v12,Dual,5g,True,False,False,Octa Core Processor,...,1080x2400,NaN,Water Drop Notch,"[64, 8, 5]",3,64.0,32.0,1,Dedicated,1024.0

In [11]:
smartphones.shape

(968, 27)

In [12]:
smartphones.isna().sum()

model                      0
price                      0
rating                     0
os                        26
sim_type                   0
network_type               0
VoLTE                      0
NFC                        0
ir_blaster                 0
chipset                    0
core_type                  6
clock_ghz                 41
ram_gb                     0
storage_gb                 0
battery_mah               11
fast_charge_w            204
screen_size_in             1
resolution                 1
refresh_rate_hz          360
display_type              85
rear_camera_mp_list        0
rear_camera_count          0
rear_camera_max_mp        16
front_camera_mp           25
memory_card_supported      0
memory_card_type         127
memory_card_max_gb       468
dtype: int64

In [13]:
smartphones.dtypes

model                     object
price                      int64
rating                   float64
os                        object
sim_type                  object
network_type              object
VoLTE                       bool
NFC                         bool
ir_blaster                  bool
chipset                   object
core_type                 object
clock_ghz                float64
ram_gb                     int64
storage_gb                 int64
battery_mah              float64
fast_charge_w            float64
screen_size_in           float64
resolution                object
refresh_rate_hz          float64
display_type              object
rear_camera_mp_list       object
rear_camera_count          int64
rear_camera_max_mp       float64
front_camera_mp          float64
memory_card_supported      int64
memory_card_type          object
memory_card_max_gb       float64
dtype: object

In [14]:
smartphones.columns

Index(['model', 'price', 'rating', 'os', 'sim_type', 'network_type', 'VoLTE',
       'NFC', 'ir_blaster', 'chipset', 'core_type', 'clock_ghz', 'ram_gb',
       'storage_gb', 'battery_mah', 'fast_charge_w', 'screen_size_in',
       'resolution', 'refresh_rate_hz', 'display_type', 'rear_camera_mp_list',
       'rear_camera_count', 'rear_camera_max_mp', 'front_camera_mp',
       'memory_card_supported', 'memory_card_type', 'memory_card_max_gb'],
      dtype='object')

In [15]:
smartphones["os"].unique()

array(['Android v13', 'Android v12', 'iOS v16', 'iOS v15', 'Android v11',
       'Android v10', 'iOS v13', nan, 'HarmonyOS v2', 'iOS v15.0',
       'iOS v14', 'Android v10.0', 'Android v8.1 (Oreo)', 'iOS v13.0',
       'Android v11.0', 'Android v9.0 (Pie)', 'Android v12.1',
       'iOS v12.3', 'KAI OS', 'iOS v17', 'Android v4.4.2 (KitKat)',
       'Android v5.1 (Lollipop)', 'Hongmeng OS v3.0', '0',
       'Android v8.0 (Oreo)', 'Pragati OS (Powered by Android)',
       'iOS v10', 'iOS v14.0', 'Harmony v2.0', 'Hongmeng OS v4.0',
       'HarmonyOS v2.0', 'EMUI v12', 'HarmonyOS', 'Android',
       'Android v9 (Pie)', 'Android v6.0 (Marshmallow)'], dtype=object)

In [16]:
smartphones["battery_mah"].nunique()

88

In [17]:
smartphones["battery_mah"].unique()

array([ 5000.,  3279.,  4980.,  4500.,  3240.,  4700.,  4830.,  4800.,
        4323.,  3110.,  5200.,  6000.,  4325.,  4600.,  4200.,  3500.,
        3095.,  4020.,  3200.,  4400.,  4310.,  4820.,  3700.,  5160.,
          nan,  5080.,  3900.,  4410.,  5020.,  2800.,  4352.,  4520.,
        4810.,  4000.,  2050.,  2150.,  4610.,  5100.,  7000.,  4300.,
        5500.,  4050.,  4355.,  3060.,  5003.,  2438.,  4250.,  3300.,
        4450.,  4614.,  4870.,  4030.,  4350.,  4100., 21000.,  2000.,
        4860.,  2275.,  4230.,  1900.,  4730.,  1500.,  3520.,  4080.,
        5050.,  5600.,  4470.,  3360.,  3000.,  2230.,  9800.,  1821.,
        4015.,  3285.,  4360.,  3315.,  3600.,  3100., 22000.,  4532.,
        5065.,  4620.,  4780.,  3730.,  3400.,  2730.,  5180.,  8000.,
        3020.])

In [18]:
smartphones["core_type"].unique()

array(['Octa Core', 'Hexa Core', 'Quad Core', nan, 'Dual Core'],
      dtype=object)

In [19]:
smartphones["sim_type"].nunique()

2

In [20]:
smartphones["sim_type"].unique()

array(['Dual', 'Single'], dtype=object)

In [21]:
smartphones["core_type"].nunique()

4

In [22]:
smartphones["refresh_rate_hz"].nunique()

5

In [23]:
smartphones["refresh_rate_hz"].unique()

array([120.,  90.,  nan, 144., 165., 240.])

In [24]:
smartphones["display_type"].unique()

array(['Punch Hole', 'Water Drop Notch', 'Small Notch', nan,
       'Large Notch', 'Dual Punch Hole'], dtype=object)

In [25]:
smartphones["display_type"].nunique()

5

In [26]:
smartphones["display_type"].unique()

array(['Punch Hole', 'Water Drop Notch', 'Small Notch', nan,
       'Large Notch', 'Dual Punch Hole'], dtype=object)

In [27]:
smartphones.dropna(inplace=True)

In [28]:
smartphones

,model,price,rating,os,sim_type,network_type,VoLTE,NFC,ir_blaster,chipset,...,resolution,refresh_rate_hz,display_type,rear_camera_mp_list,rear_camera_count,rear_camera_max_mp,front_camera_mp,memory_card_supported,memory_card_type,memory_card_max_gb
1,oneplus nord ce 2 lite 5g,19989,81.0,Android v12,Dual,5g,True,False,False,Snapdragon 695,...,1080x2412,120.0,Punch Hole,"[64, 2, 2]",3,64.0,16.0,1,Hybrid,1024.0
2,samsung galaxy a14 5g,16499,75.0,Android v13,Dual,5g,True,False,False,Exynos 1330,...,1080x2408,90.0,Water Drop Notch,"[50, 2, 2]",3,50.0,13.0,1,Dedicated,1024.0
5,samsung galaxy f23 5g,16999,80.0,Android v12,Dual,5g,True,True,False,Snapdragon 750G,...,1080x2408,120.0,Water Drop Notch,"[50, 8, 2]",3,50.0,8.0,1,Dedicated,1024.0
10,realme 10 pro,18999,82.0,Android v13,Dual,5g,True,False,False,Snapdragon 695,...,1080x2400,120.0,Punch Hole,"[108, 2]",2,108.0,16.0,1,Dedicated,1024.0
13,vivo t1 5g,16990,80.0,Android v12,Dual,5g,True,False,False,Snapdragon 695,...,1080x2408,120.0,Water Drop Notch,"[50, 2, 2]",3,50.0,16.0,1,Hybrid,1024.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
917,oppo reno 5a,22990,80.0,Android v11,Dual,5g,True,False,False,Snapdragon 765G,...,1080x2400,90.0,Punch Hole,[64],1,64.0,16.0,1,Dedicated,1024.0
921,realme 8i,12499,74.0,Android v11,Dual,4g,True,False,False,Helio G96,...,1080x2412,120.0,Punch Hole,"[50, 2, 2]",3,50.0,16.0,1,Dedicated,256.0
927,samsung galaxy f12,10499,73.0,Android v11,Dual,4g,True,False,False,Exynos 850,...,720x1600,90.0,Water Drop Notch,[48],1,48.0,8.0,1,Dedicated,512.0
932,oppo a53 2020,13990,70.0,Android v10,Dual,4g,True,False,False,Snapdragon 460,...,1600x720,90.0,Punch Hole,"[13, 2, 2]",3,13.0,16.0,1,Dedicated,256.0
950,oppo a58x,13990,72.0,Android v12,Dual,5g,True,False,False,Dimensity 700 5G,...,720x1612,90.0,Water Drop Notch,"[13, 2]",2,13.0,8.0,1,Dedicated,1024.0

In [32]:
smartphones.shape

(234, 27)

In [33]:
smartphones.describe()

,price,rating,clock_ghz,ram_gb,storage_gb,battery_mah,fast_charge_w,screen_size_in,refresh_rate_hz,rear_camera_count,rear_camera_max_mp,front_camera_mp,memory_card_supported,memory_card_max_gb
count,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.000000,234.0,234.000000
mean,20133.880342,79.504274,2.273889,6.260684,6.260684,5099.871795,34.094017,6.580256,103.487179,2.320513,62.299145,15.893162,1.0,848.957265
std,11481.108403,4.544721,0.252221,1.709728,1.709728,1186.262382,23.767104,0.112463,15.681714,0.856587,25.873335,8.387178,0.0,323.729617
min,7990.000000,65.000000,1.600000,3.000000,3.000000,4000.000000,10.000000,6.200000,90.000000,1.000000,12.000000,5.000000,1.0,256.000000
25%,14489.250000,76.000000,2.200000,4.500000,4.500000,5000.000000,18.000000,6.500000,90.000000,1.000000,50.000000,8.000000,1.0,512.000000
50%,16999.000000,80.000000,2.200000,6.000000,6.000000,5000.000000,31.500000,6.590000,90.000000,3.000000,50.000000,16.000000,1.0,1024.000000
75%,21993.750000,83.000000,2.400000,8.000000,8.000000,5000.000000,33.000000,6.670000,120.000000,3.000000,64.000000,16.000000,1.0,1024.000000
max,104999.000000,89.000000,3.200000,12.000000,12.000000,22000.000000,210.000000,6.950000,144.000000,3.000000,200.000000,60.000000,1.0,2048.000000

In [34]:
smartphones.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234 entries, 1 to 950
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   model                  234 non-null    object
 1   price                  234 non-null    int64
 2   rating                 234 non-null    float64
 3   os                     234 non-null    object
 4   sim_type               234 non-null    object
 5   network_type           234 non-null    object
 6   VoLTE                  234 non-null    bool
 7   NFC                    234 non-null    bool
 8   ir_blaster             234 non-null    bool
 9   chipset                234 non-null    object
 10  core_type              234 non-null    object
 11  clock_ghz              234 non-null    float64
 12  ram_gb                 234 non-null    int64
 13  storage_gb             234 non-null    int64
 14  battery_mah            234 non-null    float64
 15  fast_charge_w          234 non-null    float64
 16  screen_size_in         234 non-null    float64
 17  resolution             234 non-null    object
 18  refresh_rate_hz        234 non-null    float64
 19  display_type           234 non-null    object
 20  rear_camera_mp_list    234 non-null    object
 21  rear_camera_count      234 non-null    int64
 22  rear_camera_max_mp     234 non-null    float64
 23  front_camera_mp        234 non-null    float64
 24  memory_card_supported  234 non-null    int64
 25  memory_card_type       234 non-null    object
 26  memory_card_max_gb     234 non-null    float64
dtypes: bool(3), float64(9), int64(5), object(10)
memory usage: 46.4+ KB